using System;
using System.Collections.Generic;

#nullable disable

namespace GenerateModelsFromDB.Models
{
    public partial class LstProduct
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Name2 { get; set; }
        public string Uom { get; set; }
        public bool? InventoryYn { get; set; }
        public byte? CostType { get; set; }
        public string Type { get; set; }
        public string Group1 { get; set; }
        public string Group2 { get; set; }
        public string Group3 { get; set; }
        public bool? LotYn { get; set; }
        public int? SiteId { get; set; }
        public string MaViTri { get; set; }
        public string MaThue { get; set; }
        public string MaThueNk { get; set; }
        public bool? KkYn { get; set; }
        public decimal? SlMin { get; set; }
        public decimal? SlMax { get; set; }
        public string TkVt { get; set; }
        public bool? SuaTkVt { get; set; }
        public string TkGv { get; set; }
        public string TkDt { get; set; }
        public string TkDtnb { get; set; }
        public string TkTl { get; set; }
        public string TkDl { get; set; }
        public string TkSpdd { get; set; }
        public string TkClVt { get; set; }
        public string TkCk { get; set; }
        public string TkCpbh { get; set; }
        public decimal? KieuLo { get; set; }
        public decimal? CachXuat { get; set; }
        public decimal? SoNgaySp { get; set; }
        public decimal? SoNgayBh { get; set; }
        public bool? TaoLo { get; set; }
        public string OngBa { get; set; }
        public string MaKh0 { get; set; }
        public string MaKh2 { get; set; }
        public string MaKh { get; set; }
        public decimal? Height { get; set; }
        public decimal? Length { get; set; }
        public decimal? Volume { get; set; }
        public decimal? Weight { get; set; }
        public decimal? Width { get; set; }
        public decimal? Density { get; set; }
        public decimal? Depth { get; set; }
        public decimal? Diameter { get; set; }
        public decimal? Gauge { get; set; }
        public decimal? Height0 { get; set; }
        public decimal? Length0 { get; set; }
        public decimal? Volume0 { get; set; }
        public decimal? Weight0 { get; set; }
        public decimal? Width0 { get; set; }
        public string Xsize { get; set; }
        public string Xstyle { get; set; }
        public string Xcolor { get; set; }
        public decimal? Weight2 { get; set; }
        public string Dvtheight { get; set; }
        public string Dvtlength { get; set; }
        public string Dvtvolume { get; set; }
        public string Dvtweight { get; set; }
        public string Dvtwidth { get; set; }
        public string Dvtdensity { get; set; }
        public string Dvtdepth { get; set; }
        public string Dvtdiameter { get; set; }
        public string Dvtgauge { get; set; }
        public string Dvtheight0 { get; set; }
        public string Dvtlength0 { get; set; }
        public string Dvtvolume0 { get; set; }
        public string Dvtweight0 { get; set; }
        public string Dvtwidth0 { get; set; }
        public string Dvtweight2 { get; set; }
        public decimal? Packs { get; set; }
        public string Dvtpacks { get; set; }
        public string PackSize { get; set; }
        public string NuocSx { get; set; }
        public decimal? TgTh { get; set; }
        public decimal? SlLoChuan { get; set; }
        public string DvttgTh { get; set; }
        public string DvtslLoChuan { get; set; }
        public string GhiChu { get; set; }
        public DateTime? NgayMua { get; set; }
        public decimal? KieuHd { get; set; }
        public decimal? TonAt { get; set; }
        public decimal? CoLo { get; set; }
        public decimal? SoNgayDh { get; set; }
        public decimal? SlDatKt { get; set; }
        public decimal? VungHd { get; set; }
        public string MaLoTrinh { get; set; }
        public string Status { get; set; }
        public DateTime? Datetime0 { get; set; }
        public DateTime? Datetime2 { get; set; }
        public decimal? UserId0 { get; set; }
        public decimal? UserId2 { get; set; }
        public string MaTd1 { get; set; }
        public string MaTd2 { get; set; }
        public string MaTd3 { get; set; }
        public decimal? SlTd1 { get; set; }
        public decimal? SlTd2 { get; set; }
        public decimal? SlTd3 { get; set; }
        public DateTime? NgayTd1 { get; set; }
        public DateTime? NgayTd2 { get; set; }
        public DateTime? NgayTd3 { get; set; }
        public string GcTd1 { get; set; }
        public string GcTd2 { get; set; }
        public string GcTd3 { get; set; }
        public string S1 { get; set; }
        public string S2 { get; set; }
        public string S3 { get; set; }
        public decimal? S4 { get; set; }
        public decimal? S5 { get; set; }
        public decimal? S6 { get; set; }
        public DateTime? S7 { get; set; }
        public DateTime? S8 { get; set; }
        public DateTime? S9 { get; set; }
    }
}
